# Generated by Django 4.2.2 on 2023-07-05 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=100)),
                ('logo_marca', models.ImageField(blank=True, upload_to='')),
                ('catalogo_pdf', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_producto', models.CharField(max_length=200)),
                ('codigo_producto', models.CharField(max_length=200)),
                ('unidadMedida_producto', models.CharField(max_length=200)),
                ('imagen_producto', models.ImageField(blank=True, upload_to='')),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CalenaApp.categoria')),
                ('marca_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CalenaApp.marca')),
            ],
        ),
    ]
